import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Box } from "@mui/material";
import { Space } from "@/components/Space";
import { TopBar } from "@/components/TopBar/TopBar";

export default function Start() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Box
        className={styles.main}
        sx={{ backgroundColor: "#f5f5f5" }}
        justifyContent="center"
      >
        <Box
          sx={{
            borderRadius: "50px",
            background: "#f5f5f5",
            boxShadow: "13px 13px 20px #aeaeae, -13px -13px 20px #ffffff",
          }}
          width={350}
          height={350}
          justifyContent="center"
          alignItems="center"
          display={"flex"}
          flexDirection="column"
        >
          <Image
            src={"/assets/only-logo.svg"}
            width={300}
            height={300}
            alt="fågla app logo"
          ></Image>
        </Box>
        <Space size={40} />
        <Image
          src={"/assets/text-logo.svg"}
          width={200}
          height={100}
          alt="fågla text logo"
        ></Image>
      </Box>
    </>
  );
}
