import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Box, Grid, Typography } from "@mui/material";
import { Space } from "@/components/Space";
import { TopBar } from "@/components/TopBar/TopBar";
import { FullLogo } from "@/components/FullLogo/FullLogo";

export default function Start() {
  return (
    <Box
      sx={{
        backgroundColor: "#f5f5f5",
        backgroundImage: "url('/assets/bg_2.svg')",
        backgroundSize: "cover",
        minHeight: "100vh",
        display: "flex",
        justifyContent: "center",
      }}
    >
      <Head>
        <title>Fågla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TopBar /> */}
      <Grid
        container
        spacing={4}
        padding={{ xs: 4, sm: 6, md: 12 }}
        maxWidth="2000px"
        width={"100%"}
      >
        <Grid item direction="row" sm={6}>
          {/* <FullLogo /> */}
          <Image
            src={"/assets/mobile_1.png"}
            style={
              {
                // width: "100%",
                // height: "100%",
              }
            }
            width={2401 / 4}
            height={2932 / 4}
            alt="fågla app logo"
          />
        </Grid>
        <Grid item sm={6} direction="row">
          <Space size={50} />
          <Typography variant="h1">Fågla - Appen för fågelskådare</Typography>
          <Space size={12} />
          <Typography fontSize={24} fontWeight={500}>
            Fågla ger dig statistik över din egen samt andras fågelrapporter.
            Med en omfattande databas över fågelobservationer kan du söka efter
            specifika arter, jaga nya kryss eller samla pins.
          </Typography>
          <Box display={"flex"} alignItems="center">
            <a
              href=""
              style={{
                display: "inline-block",
                overflow: "hidden",
                borderRadius: "13px",
                width: "150px",
                height: "83px",
              }}
            >
              <img
                src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/sv-se?size=250x83&amp;releaseDate=1553731200"
                alt="Download on the App Store"
                style={{
                  borderRadius: "13px",
                  width: "150px",
                  height: "83px",
                }}
              />
            </a>
            <Space size={24} />
            <Image
              src={"/assets/google-play-badge.png"}
              width={240 / 1.5}
              height={93 / 1.5}
              alt="fågla app logo"
            />
          </Box>
          {/* <Space size={150} /> */}
          {/* <Box>
            <Typography variant="h1">Fågla - för fågelskådare</Typography>
            <Space size={8} />

            <Typography>
              Att vistas naturen och dess skönhet är en fantastisk upplevelse.
              Det finns få saker som kan jämföras med att sätta sig i skogen och
              lyssna på fåglarnas sång eller se dem flyga fritt i himlen. För
              fågelskådare är denna upplevelse särskilt betydelsefull. Oavsett
              om du är en erfaren fågelskådare eller bara vill börja utforska
              denna spännande hobby, kan Fågla vara en fantastisk tillgång.
              <br />
              <br />
              Fågla låter dig rapportera fåglar du sett, lära dig mer om deras
              beteenden och vanor, och få en djupare förståelse för naturen runt
              omkring dig. Genom att ha tillgång till en databas med
              fågelobservationer kan du lättare hitta olika arter baserat på
              deras utbredningsområden.
              <br />
              <br />
              Med sociala funktioner kan du också ansluta till en community av
              andra fågelskådare, dela dina upptäckter och ta del av andras.
              Appen ger också tillgång till fågelstatistik som ger en överblick
              över vilka fåglar som observeras mest i olika områden och under
              olika årstider. Med Fågla kan du inte bara fördjupa din kunskap
              och förståelse för fåglar, utan också ansluta till en större
              gemenskap av fågelskådare.
              <br />
              <br />
              Appen kan hjälpa dig att ta din fågelskådarupplevelse till en ny
              nivå genom att ge dig möjlighet att spåra dina observationer,
              ansluta till andra skådare i ditt område, samla pins och ta del av
              information om vilka fåglar som observeras mest i ditt område. Med
              hjälp av teknologi kan du utforska naturen på ett mer djupgående
              sätt och ta del av den fantastiska skönheten som fåglarna har att
              erbjuda.
            </Typography>
          </Box> */}
        </Grid>
      </Grid>
    </Box>
  );
}
